# -- Main Menu --
[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Writeups"
  pageRef = "writeups"
  weight = 20

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 30

[[main]]
  name = "About Me"
  pageRef = "about"
  weight = 40

