# -- Theme Options --
colorScheme = "terminal"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

mainSections = ["writeups", "posts"]
disableTextInHeader = true

[header]
  layout = "basic"

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 1
  showMoreLink = true
  showMoreLinkDest = "/writeups/"

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = true
  showAuthor = false
  showHero = false
  heroStyle = "basic"
  showBreadcrumbs = true
  showDraftLabel = true
  showTableOfContents = true
  showHeadingAnchors = true
  showPagination = true
  showWordCount = true
  showReadingTime = true
  showTags = false

[list]
  showTableOfContents = false
  showBreadcrumbs = true
  showSummary = true
  cardView = false
  groupByYear = true
  paginationWidth = 1
